spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:board
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
